### ISSUE TITLE
Connection pooling wait_timeout issue

### ISSUE THREAD

**Issue by jitendratheta** [minnal/minnal#127]
When connection is idle for more than the mysql server "wait_timeout" period (defined at mysql server end), Connections gets closed and any further operation fails with following stack trace.

Seems like c3P0 not checking out a new connection if this occurs. What could be done to avoid this?
# 

Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 206,186,144 milliseconds ago.  The last packet sent successfully to the server was 206,186,144 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:534)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
    at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
    at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3853)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2471)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2677)
#     at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2134)

**Comment by jitendratheta** [comment]
Any Updates ?

**Comment by ganeshs** [comment]
This is not an issue with minnal. You will have to configure c3p0
configuration to test for idle connections.

Check the doc
http://minnal.github.io/minnal/manual/core.html?highlight=pool#database-configuration
for db configurations available.

http://stackoverflow.com/questions/27034396/the-last-packet-successfully-received-from-the-server-was-109-253-milliseconds-a

-Ganesh

**Comment by jitendratheta** [comment]
Ok. Adding flag "hibernate.c3p0.idle_test_period"
based on information at http://www.mchange.com/projects/c3p0/index.html#configuring_connection_testing
